VKP-75-docker: Поднять docker containers с Redis, Postgres и Go app
go-park-mail-ru/2024_1_VKPogromisty pull request #18
Opened 2024-03-17 20:24 UTC by Petr09Mitin

2024-03-18 08:02 UTC, TheVovchenskiy requested changes

2024-03-18 08:02 UTC, TheVovchenskiy commented on Dockerfile
> +FROM golang:alpine
лучше сразу явно указывать версию образа (не `latest`), чтобы точно гарантирвоать, что твоя программа будет работать

2024-03-18 08:02 UTC, TheVovchenskiy commented on Dockerfile
собирать образы Go приложений лучше в несколько этапов https://docs.docker.com/language/golang/build-images/#multi-stage-builds

2024-03-18 08:02 UTC, TheVovchenskiy commented on docker-compose.yml
> +      - socio
по умолчанию для всех твоих запущенных контейнеров уже создается внутренняя сеть [ссылка](https://docs.docker.com/compose/networking/), подумай, надо ли тебе отдельно создавать свою новую сеть.

2024-03-18 08:02 UTC, TheVovchenskiy commented on docker-compose.yml
> +    image: postgres:latest
тут тоже лучше версию явно указывать

2024-03-18 08:02 UTC, TheVovchenskiy commented on docker-compose.yml
> +    image: redis:latest
и тут

2024-03-18 08:02 UTC, TheVovchenskiy commented on docker-compose.yml
> +    container_name: golang_container
для своих контейнеров подумай проставлять тэги для версионирования, чтобы в случае какого-то бага на проде можно было быстро перезапустить контейнер с более старой, но стабильной версией

2024-03-18 08:11 UTC, Petr09Mitin commented on Dockerfile
> +FROM golang:alpine
Fixed

2024-03-18 08:11 UTC, Petr09Mitin commented on docker-compose.yml
> +    image: postgres:latest
Fixed

2024-03-18 08:12 UTC, Petr09Mitin commented on docker-compose.yml
> +    image: redis:latest
Fixed

2024-03-18 08:13 UTC, Petr09Mitin commented on docker-compose.yml
> +      - socio
Fixed

2024-03-18 08:25 UTC, Petr09Mitin commented on docker-compose.yml
> +    container_name: golang_container
Fixed

2024-03-18 17:54 UTC, Petr09Mitin commented on Dockerfile
Fixed

2024-03-19 05:41 UTC, TheVovchenskiy approved these changes

2024-03-19 14:04 UTC, merged