VKP-46-subs: Добавить API подписок
go-park-mail-ru/2024_1_VKPogromisty pull request #21
Opened 2024-03-21 21:42 UTC by Petr09Mitin

2024-03-22 00:39 UTC, TheVovchenskiy requested changes

2024-03-22 00:39 UTC, TheVovchenskiy commented on domain/subscription.go
> +	SubscribedToID uint                  `json:"subscribed_to"`
микро момент: у json названия полей в одном стиле - camel case

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +}
не совсем понимаю, зачем эта структура нужна? нигде ее больше не нашел

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +		err = rows.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.Avatar, &user.DateOfBirth.Time, &user.RegistrationDate.Time)
давай здесь для лучше читаемости аргументы не в одной строке расположим, а построчно

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +			err = errors.ErrInternal
а зачем ты здесь отправляешь эту ошибку, если у тебя в конце все равно маппинг ошибок происходит, и по-умолчанию вернется 500? Давай не будем лишний раз эту ошибку возвращать, мало ли где нам понадобится оригинальная ошибка. Такое не только тут увидел, поэтому поправь везде

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	row := s.db.QueryRow("INSERT INTO subscriptions (subscriber, subscribed_to, creation_date) VALUES ($1, $2, $3) RETURNING id, subscriber, subscribed_to, creation_date", sub.SubscriberID, sub.Subscrib
давай здесь не в одну строку все, а то сложно читать

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	row := s.db.QueryRow("INSERT INTO subscriptions (subscriber, subscribed_to, creation_date) VALUES ($1, $2, $3) RETURNING id, subscriber, subscribed_to, creation_date", sub.SubscriberID, sub.Subscrib
и еще момент, можно же не отпралять значение времени `creation_date`, оно по-умолачнию заполнится само

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	_, err = s.db.Exec("DELETE FROM subscriptions WHERE id = $1", subscriptionID)
при выполнении `Exec()` нужно немножко по-другому обрабатывать ошибки, посмотри как в [примере](https://pkg.go.dev/database/sql#DB.ExecContext)

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	err = s.db.QueryRow("SELECT id, subscriber, subscribed_to, creation_date FROM subscriptions WHERE subscriber = $1 AND subscribed_to = $2", subscriberID, subscribedToID).Scan(&subscription.ID, &subsc
разнеси по строкам, для лучшей читаемости

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	`, userID)
для `Query()` посмотри в [доке](https://pkg.go.dev/database/sql#DB.QueryContext) пример, как правильно ошибки отлавливать, не забудь про `rows.Close()`. Везде, где используется `Query()` поправь

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +	row := s.db.QueryRow("INSERT INTO subscriptions (subscriber, subscribed_to, creation_date) VALUES ($1, $2, $3) RETURNING id, subscriber, subscribed_to, creation_date", sub.SubscriberID, sub.Subscrib
также для `QueryRow()` посмотри [обработку ошибок](https://pkg.go.dev/database/sql#DB.QueryRowContext)

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
прости, я в прошлый раз вообще моменты с обработкой ошибок и читаемостью пропустил, поправь в остальных репозиториях аналогично

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/rest/subscriptions.go
> +	SubscribedToID uint `json:"subscribed_to"`
поля json в camelcase

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/rest/subscriptions.go
> +		json.ServeJSONError(w, errors.ErrJSONUnmarshalling)
а почему тут `return` не ставишь?

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/rest/subscriptions.go
> +		json.ServeJSONError(w, errors.ErrJSONUnmarshalling)
и тут

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/rest/subscriptions.go
> +	}
здесь и далее подобную проверку надо вынести в отдельную middleware и оборачивать отдельные ручки, которые требуют авторизации, чтобы копипаста не было

2024-03-22 00:39 UTC, TheVovchenskiy commented on internal/repository/postgres/subscriptions.go
> +func (s *Subscriptions) GetByData(subscriberID uint, subscribedToID uint) (subscription *domain.Subscription, err error) {
не совсем понятно, что делает этот метод, давай переназовем его

2024-03-22 00:39 UTC, TheVovchenskiy commented on usecase/subscriptions/subscriptions.go
> +	}
ты тут ходишь 4 раза базу данных, мне кажется это все можно одним запросом сделать, чтобы ее сильно не нагружать, давай оптимизируем этот момент

2024-03-22 00:39 UTC, TheVovchenskiy commented on usecase/subscriptions/subscriptions.go
> +	}
здесь и далее аналогично

2024-03-22 07:45 UTC, Petr09Mitin commented on domain/subscription.go
> +	SubscribedToID uint                  `json:"subscribed_to"`
Fixed

2024-03-22 07:45 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +}
Fixed

2024-03-22 07:46 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +		err = rows.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.Avatar, &user.DateOfBirth.Time, &user.RegistrationDate.Time)
Fixed

2024-03-22 07:50 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +			err = errors.ErrInternal
Fixed

2024-03-22 07:57 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +	row := s.db.QueryRow("INSERT INTO subscriptions (subscriber, subscribed_to, creation_date) VALUES ($1, $2, $3) RETURNING id, subscriber, subscribed_to, creation_date", sub.SubscriberID, sub.Subscrib
Fixed

2024-03-22 08:22 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +	_, err = s.db.Exec("DELETE FROM subscriptions WHERE id = $1", subscriptionID)
Fixed

2024-03-22 08:25 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +	err = s.db.QueryRow("SELECT id, subscriber, subscribed_to, creation_date FROM subscriptions WHERE subscriber = $1 AND subscribed_to = $2", subscriberID, subscribedToID).Scan(&subscription.ID, &subsc
Fixed

2024-03-22 09:04 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +func (s *Subscriptions) GetByData(subscriberID uint, subscribedToID uint) (subscription *domain.Subscription, err error) {
Fixed

2024-03-22 09:05 UTC, Petr09Mitin commented on internal/rest/subscriptions.go
> +	SubscribedToID uint `json:"subscribed_to"`
Fixed

2024-03-22 09:06 UTC, Petr09Mitin commented on internal/rest/subscriptions.go
> +		json.ServeJSONError(w, errors.ErrJSONUnmarshalling)
Fixed

2024-03-22 09:06 UTC, Petr09Mitin commented on internal/rest/subscriptions.go
> +		json.ServeJSONError(w, errors.ErrJSONUnmarshalling)
Fixed

2024-03-22 10:38 UTC, Petr09Mitin commented on internal/rest/subscriptions.go
> +	}
Fixed

2024-03-22 10:48 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
> +	`, userID)
Fixed

2024-03-22 10:48 UTC, Petr09Mitin commented on internal/repository/postgres/subscriptions.go
Fixed

2024-03-22 11:46 UTC, Petr09Mitin commented on usecase/subscriptions/subscriptions.go
> +	}
Fixed

2024-03-22 11:46 UTC, Petr09Mitin commented on usecase/subscriptions/subscriptions.go
> +	}
Fixed

2024-03-23 11:40 UTC, TheVovchenskiy approved these changes

2024-03-23 17:10 UTC, merged