Vkp 68 middleware
go-park-mail-ru/2024_1_VKPogromisty pull request #30
Opened 2024-04-04 20:51 UTC by Petr09Mitin

2024-04-04 21:47 UTC, TheVovchenskiy requested changes

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/rest/middleware/logger.go
> +}
Давай логи писать в файл и в формате `json`, чтобы они были всегда в одном месте и их можно было просматривать после перезапуска контейнеров

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/rest/middleware/logger.go
> +			zap.Duration("work_time", time.Since(start)),
я не совсем понимаю, а что тут `work_time` меряет? Тут же не происходит ничего с момента `start`

2024-04-04 21:47 UTC, TheVovchenskiy commented on usecase/chat/chat.go
>  			fmt.Println("here")
этот принт давай уберем

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/postgres/users.go
> +	)
давай здесь чуствительную информацию логгировать не будем, это не очень хорошая практика

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/postgres/users.go
> +	)
тут тоже

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/postgres/users.go
> +
и тут

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/redis/session.go
> +
логирование `sessionID` тоже может быть не очень хорошей идеей, давай подумаем, как это исправить

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/redis/session.go
> +
сдесь тоже

2024-04-04 21:47 UTC, TheVovchenskiy commented on internal/repository/redis/session.go
> +
и здесь

2024-04-05 06:41 UTC, Petr09Mitin commented on internal/rest/middleware/logger.go
> +}
Done

2024-04-05 06:45 UTC, Petr09Mitin commented on internal/rest/middleware/logger.go
> +			zap.Duration("work_time", time.Since(start)),
Fixed

2024-04-05 06:46 UTC, Petr09Mitin commented on usecase/chat/chat.go
>  			fmt.Println("here")
Done

2024-04-05 11:57 UTC, TheVovchenskiy commented on usecase/auth/auth.go
> +		fmt.Println(err)
не совсем понял, а зачем эти принты?

2024-04-05 11:57 UTC, TheVovchenskiy commented on app/routers/root.go
> +	//rootRouter.Use(middleware.Recovery)
а почему эта мидлварина закоменчена?

2024-04-05 12:03 UTC, TheVovchenskiy approved these changes

2024-04-05 12:05 UTC, merged